### ISSUE TITLE
Change the taskbar icon to the Google Music icon (or similar)

### ISSUE THREAD

**Issue by AngelEzquerra** [twolfson/google-music-electron#17]
Currently Google Music Electron uses the generic "electron" icon for the taskbar item on Windows. It would be much nicer if it used a non generic "Google Music inspired" icon instead.

**Comment by twolfson** [comment]
I don't follow your example -- the icon should be a pair of headphones in the tray. Can you provide a screenshot?

**Comment by AngelEzquerra** [comment]
I was referring to the "taskbar" icon, not the taskbar icon. This also applies to the "window icon", i.e. the one that is shown (on Windows) on the top left side of the window title bar, and which when clicked shows the "Restore, Move, Size, Close" dialog. Both icons show the generic, green-blue "electron icon". It would be nicer if it showed a music inspired icon instead (e.g. the one on the system tray).

![generic_icon](https://cloud.githubusercontent.com/assets/6682868/10638453/446b921c-780b-11e5-9627-3cb45b5d7931.png)

**Comment by twolfson** [comment]
Ah, nice catch. Yea, we should add support for that.

**Comment by AngelEzquerra** [comment]
Cool. Nice to see that you understood what I meant even though I said "I was referring to the "taskbar" icon, not the taskbar icon" when I meant "I was referring to the "taskbar" icon, not the system tray icon" :-)

**Comment by twolfson** [comment]
Taking a look at this now

**Comment by twolfson** [comment]
This has been patched/released in `1.20.0`. I think we might need larger icons since it's being scaled up in the Windows tray but I would like to se what size OS X needs as well.

![selection_181](https://cloud.githubusercontent.com/assets/902488/10656130/4d01e04e-7841-11e5-8031-84bd5ae91d86.png)

![selection_180](https://cloud.githubusercontent.com/assets/902488/10656131/4f42772e-7841-11e5-9629-af609bc2b882.png)
