### ISSUE TITLE
Trying to install the mpris service globally throws a "permission denied" error

### ISSUE THREAD

**Issue by urandom** [twolfson/google-music-electron#35]
Hi,

Running `sudo google-music-electron install-mrpis` results in the following error:

```
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/google-music-electron/node_modules/electron-prebuilt/electron-tmp-download-15791-1451892115478'
    at Error (native)

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/google-music-electron/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--runtime=electron" "--target=0.34.5" "--arch=x64"
npm ERR! node v5.2.0
npm ERR! npm  v2.14.15
npm ERR! code ELIFECYCLE
npm ERR! electron-prebuilt@0.34.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.34.5 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/google-music-electron/node_modules/npm-debug.log
```

This really shouldn't be happening, since the parent command has been started with sudo.
As a workaround, the following command may be run prior to installing mpris:

```
sudo chmod g+w -R /usr/lib/node_modules/google-music-electron
```

**Comment by twolfson** [comment]
Yea, that's very strange. We aren't doing anything to drop permissions so I wonder why that's happening =_=

I will take a look at this by the end of the weekend.

**Comment by twolfson** [comment]
I started to move to a JS based MPRIS service to avoid this issue altogether. However, it turns out the native JS DBUS implementations are still naive.

As a result, I went on to debug this in a Vagrant environment. I was able to get everything working on Ubuntu fine. Then, I tried to reproduce on Arch Linux.

I resolved that the issue was Arch Linux has too aggressive of a `umask` by default (i.e. `0027`). This prevents "other" from taking any actions. On Ubuntu, we allow `rx` actions from "other", hence a umask of `0022`.

After adjusting the `umask`, we saw that everything was working as expected.

``` bash
$ sudo sh -c 'umask'
0027
$ umask o+rx
$ umask
0022
$ sudo sh -c 'umask'
0022
$ npm install -g google-music-electron@latest
```

As a result, we suggest adjusting the `umask` so that the `electron` application is writable by other programs.
