### ISSUE TITLE
Allow app to continue running after all windows have been closed on OS X

### ISSUE THREAD

**Issue by goronfreeman** [twolfson/google-music-electron#38]
I noticed an inconsistency with how google-music-electron handles closing application windows compared to other OS X audio apps. You should be able to close all application windows and have the music continue to play. Then clicking on the dock icon should spawn a new application window. It would also be nice to have cmd + w keybinding to close the window, like other OS X apps.

**Comment by twolfson** [comment]
Unfortunately, this is more of a browser application than an audio application. The window is directly tied to audio playback rather than playback being independent.

We could override the "close" action to hide the window but I feel like that's lying to the user (e.g. they might not realize Chrome is still draining their memory).

Thank you for reporting this issue though =)
